name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore Growth/GrowthAPI
    - name: Test
      run: dotnet test --verbosity normal Growth
  docker-image-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.0.0
    
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_IMAGE_TOKEN}}
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.0.0
      with:
        context: Growth
        file: Growth/GrowthAPI/Dockerfile
        push: true
        tags: index.docker.io/${{secrets.DOCKER_USER}}/growthapi:latest
        #${{github.sha}} uses a specific image
  deploy:
    runs-on: ubuntu-latest
    needs: docker-image-build
    steps:
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        app-name: GrowthAPI        
        publish-profile: ${{secrets.AZURE_PUBLISH_SETTINGS}}
        images: ${{secrets.DOCKER_USER}}/growthapi:latest




      
